# Generated by Django 5.2.1 on 2026-08-26 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenidos', '0005_favorito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='categoria',
            field=models.CharField(blank=True, choices=[('novedades', 'Novedades'), ('eventos', 'Eventos'), ('podcast', 'Podcast'), ('exclusivo', 'Exclusivo')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='contenido',
            name='seccion',
            field=models.CharField(blank=True, choices=[('cac_contigo', 'La CAC Contigo'), ('un_dia_con', 'Un día con'), ('del_libro_a_tu_oido', 'Del libro a tu oído'), ('exclusivo', 'Exclusivo')], max_length=50, null=True),
        ),
    ]
